const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Behaviors.jumpthru,
		C3.Behaviors.Anchor,
		C3.Behaviors.destroy,
		C3.Plugins.Spritefont2,
		C3.Plugins.TiledBg,
		C3.Plugins.Text,
		C3.Behaviors.scrollto,
		C3.Plugins.Timeline,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.LOS,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Browser.Acts.Close,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.layoutheight,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.CompareTime,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Acts.UnloadUnusedTextures,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Timeline.Acts.PlayAllTimelines,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.TiledBg.Exps.IID,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Exps.IID,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Spritefont2.Acts.AddInstanceVar,
		C3.Plugins.Timeline.Acts.StopAllTimelines,
		C3.Plugins.System.Acts.ResetPersisted,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Text.Cnds.CompareText,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Pathfinding.Acts.SetEnabled,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Behaviors.Pathfinding.Cnds.OnFailedToFindPath,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.System.Acts.SetLayoutScale,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.SetSolidCollisionFilter,
		C3.Plugins.System.Acts.SetLayerInteractive
	];
};
self.C3_JsPropNameTable = [
	{btn2Nivel1: 0},
	{btn3Nivel1: 0},
	{btnNivel1: 0},
	{builds2Nivel1: 0},
	{builds3Nivel1: 0},
	{Solid: 0},
	{Sine: 0},
	{BusNivel1: 0},
	{carnetNivel1: 0},
	{casaCulturaNivel1: 0},
	{creditosNivel1: 0},
	{vida_nvl_instancia_1: 0},
	{Platform: 0},
	{Flash: 0},
	{EcosNivel1: 0},
	{msgNum: 0},
	{flecha2Nivel1: 0},
	{imgNum: 0},
	{flechaNivel1: 0},
	{FondoNivel1: 0},
	{Menu_PantallaNivel1: 0},
	{msgNivel1: 0},
	{Jumpthru: 0},
	{ObjetosEscalados2Nivel1: 0},
	{ObjetosEscalados3Nivel1: 0},
	{ObjetosEscaladosNivel1: 0},
	{Sine2: 0},
	{PalomaNivel1: 0},
	{puertaNivel1: 0},
	{Ancla: 0},
	{PremioNivel1: 0},
	{move: 0},
	{DestroyOutsideLayout: 0},
	{RatonNivel1: 0},
	{slimePurple_moveNivel1: 0},
	{lives: 0},
	{SpriteFontNivel1: 0},
	{storesNivel1: 0},
	{streetNivel1: 0},
	{TiledBackground3Nivel1: 0},
	{torresPuceNivel1: 0},
	{vidasNivel1: 0},
	{historyNivel1: 0},
	{ScrollTo: 0},
	{cameraNivel1: 0},
	{SmogNivel1: 0},
	{PonkNivel1: 0},
	{Puerta2Nivel2: 0},
	{Piso2Nivel2: 0},
	{SpriteFont2Nivel2: 0},
	{TiledBackgroundNivel2: 0},
	{TimelineControllerNivel2: 0},
	{txtCaidaNivel2: 0},
	{BackgroundNivel2: 0},
	{CarnetNivel2: 0},
	{carnets: 0},
	{CarnetsNivel2: 0},
	{CarnetTextoNivel2: 0},
	{BoundToLayout: 0},
	{EcosNivel2: 0},
	{flechaNivel2: 0},
	{MensajePremioNivel2: 0},
	{msgsheet2_1Nivel2: 0},
	{Paloma2Nivel2: 0},
	{PalomaNivel2: 0},
	{piso_2Nivel2: 0},
	{Piso_Nivel2: 0},
	{Sólido: 0},
	{Plataforma2Nivel2: 0},
	{Plataforma_Nivel2: 0},
	{PlataformaBotNivel2: 0},
	{PlataFormaMitalNivel2: 0},
	{PonkNivel2: 0},
	{PremioNivel2: 0},
	{PuertaNivel2: 0},
	{Raton2Nivel2: 0},
	{RatonNivel2: 0},
	{repeatNivel2: 0},
	{slimePurple_moveNivel2: 0},
	{SpriteFont_3Nivel2: 0},
	{vidas: 0},
	{SpriteFont_4Nivel2: 0},
	{SpriteFontNivel2: 0},
	{TechoMitadNivel2: 0},
	{TechoNivel2: 0},
	{TeleportNivel2: 0},
	{TextNivel2: 0},
	{TiledBackground2Nivel2: 0},
	{VidasNivel2: 0},
	{msg2: 0},
	{Msg_preNivel2: 0},
	{SmogNivel2: 0},
	{flechapreNivel2: 0},
	{"1MAntenaNivel4": 0},
	{"1montañaNivel4": 0},
	{"1montviraNivel4": 0},
	{"3montañaNivel4": 0},
	{"4montañaNivel4": 0},
	{BasureroNivel4: 0},
	{Seno: 0},
	{beyonderNivel4: 0},
	{cabezaNivel4: 0},
	{cameraNivel4: 0},
	{CuadradoVioletaNivel4: 0},
	{DerechaNivel4: 0},
	{Plataforma: 0},
	{DesplazarHasta: 0},
	{Bala: 0},
	{Parpadeo: 0},
	{EcosNivel4: 0},
	{flechafinNivel4: 0},
	{flechaNivel4: 0},
	{IzquierdaNivel4: 0},
	{JuegosNivel4: 0},
	{M2AntenasNivel4: 0},
	{M3AntenasNivel4: 0},
	{M4AntenasNivel4: 0},
	{M5AntenasNivel4: 0},
	{mallaNivel4: 0},
	{MonatñaNivel4: 0},
	{montañainicioNivel4: 0},
	{montañatileCompletoNivel4: 0},
	{objetoBasuraNivel4: 0},
	{Buscarutas: 0},
	{LíneaDeVisión: 0},
	{PalomaNivel4: 0},
	{PequeCiudadVirgenNivel4: 0},
	{PequeciudSINVIRGENNivel4: 0},
	{PremioNivel4: 0},
	{Estado: 0},
	{DestruirFueraDeLaEscena: 0},
	{RataNivel4: 0},
	{roca2Nivel4: 0},
	{rocas3Nivel4: 0},
	{rocasNivel4: 0},
	{Seno2: 0},
	{slimeNivel4: 0},
	{spr_TelefericoNivel4: 0},
	{subirNivel4: 0},
	{sueloNivel4: 0},
	{tarjetaNivel4: 0},
	{TextofinalNivel4: 0},
	{textoinicioNivel4: 0},
	{tierra_3Nivel4: 0},
	{tierraMedianaNivel4: 0},
	{tierraOscuraNivel4: 0},
	{tierraPequeniaNivel4: 0},
	{unioncableNivel4: 0},
	{VioletaBajadaNivel4: 0},
	{VioletaSubidaNivel4: 0},
	{VolcanoNivel4: 0},
	{vidaTextoNivel4: 0},
	{numTarjetasNivel4: 0},
	{pinchosNivel4: 0},
	{XcierraNivel4: 0},
	{arbusto1Nivel4: 0},
	{arbusto2Nivel4: 0},
	{arbusto3Nivel4: 0},
	{arbusto4Nivel4: 0},
	{dronNivel4: 0},
	{telefericoNivel4: 0},
	{SpriteFontCarnetNivel4: 0},
	{SpriteFontNivel4: 0},
	{PonkNivel4: 0},
	{flechaNivel3: 0},
	{msg2Nivel3: 0},
	{msgNivel3: 0},
	{TechoMitadNivel3: 0},
	{CarnetColectNivel3: 0},
	{CarnetNivel3: 0},
	{CarnetsNivel3: 0},
	{chicleNivel3: 0},
	{deNivel3: 0},
	{FondoEnMosaico2Nivel3: 0},
	{FondoEnMosaico3Nivel3: 0},
	{FondoNivel3: 0},
	{IzqNivel3: 0},
	{MetaNivel3: 0},
	{PalomaNivel3: 0},
	{ParedNivel3: 0},
	{pisoNivel3: 0},
	{EcosNivel3: 0},
	{PremioNivel3: 0},
	{PuertaNivel3: 0},
	{RataNivel3: 0},
	{SpriteNivel3: 0},
	{VidaNivel3: 0},
	{VidasNivel3: 0},
	{materialToxicoNivel4: 0},
	{nuevaHierbaAzulNivel3: 0},
	{nuevaPlataformaDerechaNivel3: 0},
	{nuevaPlataformaIzquierdaNivel3: 0},
	{nuevaPlataformaNivel3: 0},
	{nuevaPuertaFrenteNivel3: 0},
	{nuevaPuertaJardinBotanicoFrenteNivel3: 0},
	{nuevaPuertaNivel3: 0},
	{nuevoArbol1Nivel3: 0},
	{nuevoArbol2Nivel3: 0},
	{nuevoArbol3Nivel3: 0},
	{nuevoArbol4Nivel3: 0},
	{nuevoArbolLamparaNivel3: 0},
	{nuevoArbustoNivel3: 0},
	{nuevoFondo1Nivel3: 0},
	{nuevoFondoArbolesNivel3: 0},
	{nuevoFondoLab1Nivel3: 0},
	{nuevoFondoLab2Nivel3: 0},
	{nuevoFondoLab3Nivel3: 0},
	{nuevoFondoLabFinalNivel3: 0},
	{nuevoFondoNivel4: 0},
	{nuevoRellenoSuelo1Nivel3: 0},
	{nuevoSLab1Nivel3: 0},
	{nuevoSLab2Nivel3: 0},
	{nuevoSLab3Nivel3: 0},
	{nuevoSLab4Nivel3: 0},
	{nuevoSLab5Nivel3: 0},
	{nuevoSLab6Nivel3: 0},
	{nuevoSLab7Nivel3: 0},
	{nuevoSLab8Nivel3: 0},
	{puertaJardinBotanicoNivel3: 0},
	{sueloLab1Nivel3: 0},
	{sueloLab2Nivel3: 0},
	{sueloLab3Nivel3: 0},
	{SpriteFontCarnetNivel3: 0},
	{SpriteFontNivel3: 0},
	{PonkNivel3: 0},
	{AlcantarillaNivel5: 0},
	{AlcantarrillaNivel5: 0},
	{AvionNivel5: 0},
	{basemilitarNivel5: 0},
	{bomberosNivel5: 0},
	{cabezaNivel5: 0},
	{CalleNivel5: 0},
	{CarnetesCuentaNivel5: 0},
	{ContenedorRosaNivel5: 0},
	{contenedorverdeNivel5: 0},
	{EcosNivel5: 0},
	{LamparaNivel5: 0},
	{MetaNivel5: 0},
	{MundoNivel5: 0},
	{Variable1: 0},
	{PalomaNivel5: 0},
	{Plataforma2Nivel5: 0},
	{PlataformaMuerteNivel5: 0},
	{PlataformaNivel5: 0},
	{plataformasNivel5: 0},
	{PremioNivel5: 0},
	{RataNivel5: 0},
	{RosaPlanoNivel5: 0},
	{RosaSEPARADONivel5: 0},
	{salidametrofondoNivel5: 0},
	{salidametrofrontalNivel5: 0},
	{SlimeNivel5: 0},
	{Sprite2Nivel5: 0},
	{SpriteNivel5: 0},
	{susbsueloNivel5: 0},
	{tarjetaNivel5: 0},
	{tarjetaTextoNivel5: 0},
	{TodoCercaNivel5: 0},
	{unsoloescenarioNivel5: 0},
	{ventanabasemilitarNivel5: 0},
	{VidaTextoNivel5: 0},
	{flechafinNivel5: 0},
	{FlechainicioNivel5: 0},
	{TextofinalNivel5: 0},
	{textoinicioNivel5: 0},
	{FondoEnMosaico2: 0},
	{arbusto1Nivel5: 0},
	{arbusto2Nivel5: 0},
	{arbusto3Nivel5: 0},
	{arbusto4Nivel5: 0},
	{basemilitarEntradaNivel5: 0},
	{SpriteFontCarnetNivel5: 0},
	{SpriteFontNivel5: 0},
	{PonkNivel5: 0},
	{beyonderNivel5: 0},
	{dronNivel5: 0},
	{AlmacenamientoLocal: 0},
	{Audio: 0},
	{CartelAdvertenciaBorradoSeleccionNivel: 0},
	{FondoEnMosaico: 0},
	{FondoSeleccion: 0},
	{fondoTransparenteConfirmarBorrado: 0},
	{IconoEliminarGuardado: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{NoBorrarProgresoSeleccionNivel: 0},
	{SeleccionNivel1: 0},
	{SeleccionNivel2: 0},
	{SeleccionNivel3: 0},
	{SeleccionNivel4: 0},
	{SeleccionNivel5: 0},
	{SiBorrarProgresoSeleccionNivel: 0},
	{TituloSeleccionarNivel: 0},
	{Touch: 0},
	{volverMenuSeleccionNivel: 0},
	{equis: 0},
	{SeleccionNivel6: 0},
	{logoEcos: 0},
	{RataNivel0: 0},
	{deNivel0: 0},
	{IzqNivel0: 0},
	{Navegador: 0},
	{plataforma: 0},
	{SeleccionarElNivel: 0},
	{FuenteSprite: 0},
	{Sprite: 0},
	{Texto_seleccion: 0},
	{dienteDeLeon: 0},
	{optimizado: 0},
	{nivelMaxActual: 0},
	{playMusic_nvl1: 0},
	{finalScene_nvl1: 0},
	{carnets_nvl1: 0},
	{vulnerable_nvl1: 0},
	{vida_nvl1: 0},
	{Jumping__lvl_2: 0},
	{TeleporFrom_lvl_2: 0},
	{tiempoCaida_lvl_2: 0},
	{vida_nvl2: 0},
	{vulnerable_nvl2: 0},
	{numTarjetas_nvl4: 0},
	{vida_nvl4: 0},
	{vulnerable_nvl4: 0},
	{numTarjetas: 0},
	{vida_nvl5: 0},
	{vulnerable_nvl5: 0},
	{playMusic: 0},
	{NumeroCarnets: 0},
	{vida_nvl3: 0},
	{vulnerable_nvl3: 0}
];

self.InstanceType = {
	btn2Nivel1: class extends self.ISpriteInstance {},
	btn3Nivel1: class extends self.ISpriteInstance {},
	btnNivel1: class extends self.ISpriteInstance {},
	builds2Nivel1: class extends self.ISpriteInstance {},
	builds3Nivel1: class extends self.ISpriteInstance {},
	BusNivel1: class extends self.ISpriteInstance {},
	carnetNivel1: class extends self.ISpriteInstance {},
	casaCulturaNivel1: class extends self.ISpriteInstance {},
	creditosNivel1: class extends self.ISpriteInstance {},
	EcosNivel1: class extends self.ISpriteInstance {},
	flecha2Nivel1: class extends self.ISpriteInstance {},
	flechaNivel1: class extends self.ISpriteInstance {},
	FondoNivel1: class extends self.ISpriteInstance {},
	Menu_PantallaNivel1: class extends self.ISpriteInstance {},
	msgNivel1: class extends self.ISpriteInstance {},
	ObjetosEscalados2Nivel1: class extends self.ISpriteInstance {},
	ObjetosEscalados3Nivel1: class extends self.ISpriteInstance {},
	ObjetosEscaladosNivel1: class extends self.ISpriteInstance {},
	PalomaNivel1: class extends self.ISpriteInstance {},
	puertaNivel1: class extends self.ISpriteInstance {},
	PremioNivel1: class extends self.ISpriteInstance {},
	RatonNivel1: class extends self.ISpriteInstance {},
	slimePurple_moveNivel1: class extends self.ISpriteInstance {},
	SpriteFontNivel1: class extends self.ISpriteFontInstance {},
	storesNivel1: class extends self.ISpriteInstance {},
	streetNivel1: class extends self.ITiledBackgroundInstance {},
	TiledBackground3Nivel1: class extends self.ITiledBackgroundInstance {},
	torresPuceNivel1: class extends self.ISpriteInstance {},
	vidasNivel1: class extends self.ISpriteInstance {},
	historyNivel1: class extends self.ITextInstance {},
	cameraNivel1: class extends self.ISpriteInstance {},
	SmogNivel1: class extends self.ISpriteInstance {},
	PonkNivel1: class extends self.ISpriteInstance {},
	Puerta2Nivel2: class extends self.ITiledBackgroundInstance {},
	Piso2Nivel2: class extends self.ITiledBackgroundInstance {},
	SpriteFont2Nivel2: class extends self.ISpriteFontInstance {},
	TiledBackgroundNivel2: class extends self.ITiledBackgroundInstance {},
	TimelineControllerNivel2: class extends self.IInstance {},
	txtCaidaNivel2: class extends self.ITextInstance {},
	BackgroundNivel2: class extends self.ITiledBackgroundInstance {},
	CarnetNivel2: class extends self.ISpriteInstance {},
	CarnetsNivel2: class extends self.ITextInstance {},
	CarnetTextoNivel2: class extends self.ISpriteInstance {},
	EcosNivel2: class extends self.ISpriteInstance {},
	flechaNivel2: class extends self.ISpriteInstance {},
	MensajePremioNivel2: class extends self.ISpriteInstance {},
	msgsheet2_1Nivel2: class extends self.ISpriteInstance {},
	Paloma2Nivel2: class extends self.ISpriteInstance {},
	PalomaNivel2: class extends self.ISpriteInstance {},
	piso_2Nivel2: class extends self.ITiledBackgroundInstance {},
	Piso_Nivel2: class extends self.ITiledBackgroundInstance {},
	Plataforma2Nivel2: class extends self.ISpriteInstance {},
	Plataforma_Nivel2: class extends self.ITiledBackgroundInstance {},
	PlataformaBotNivel2: class extends self.ITiledBackgroundInstance {},
	PlataFormaMitalNivel2: class extends self.ISpriteInstance {},
	PonkNivel2: class extends self.ISpriteInstance {},
	PremioNivel2: class extends self.ISpriteInstance {},
	PuertaNivel2: class extends self.ISpriteInstance {},
	Raton2Nivel2: class extends self.ISpriteInstance {},
	RatonNivel2: class extends self.ISpriteInstance {},
	repeatNivel2: class extends self.ISpriteInstance {},
	slimePurple_moveNivel2: class extends self.ISpriteInstance {},
	SpriteFont_3Nivel2: class extends self.ISpriteFontInstance {},
	SpriteFont_4Nivel2: class extends self.ISpriteFontInstance {},
	SpriteFontNivel2: class extends self.ISpriteFontInstance {},
	TechoMitadNivel2: class extends self.ITiledBackgroundInstance {},
	TechoNivel2: class extends self.ITiledBackgroundInstance {},
	TeleportNivel2: class extends self.ISpriteInstance {},
	TextNivel2: class extends self.ITextInstance {},
	TiledBackground2Nivel2: class extends self.ITiledBackgroundInstance {},
	VidasNivel2: class extends self.ITextInstance {},
	msg2: class extends self.ISpriteInstance {},
	Msg_preNivel2: class extends self.ISpriteInstance {},
	SmogNivel2: class extends self.ISpriteInstance {},
	flechapreNivel2: class extends self.ISpriteInstance {},
	_1MAntenaNivel4: class extends self.ISpriteInstance {},
	_1montañaNivel4: class extends self.ISpriteInstance {},
	_1montviraNivel4: class extends self.ISpriteInstance {},
	_3montañaNivel4: class extends self.ISpriteInstance {},
	_4montañaNivel4: class extends self.ISpriteInstance {},
	BasureroNivel4: class extends self.ISpriteInstance {},
	beyonderNivel4: class extends self.ISpriteInstance {},
	cabezaNivel4: class extends self.ISpriteInstance {},
	cameraNivel4: class extends self.ISpriteInstance {},
	CuadradoVioletaNivel4: class extends self.ISpriteInstance {},
	DerechaNivel4: class extends self.ISpriteInstance {},
	EcosNivel4: class extends self.ISpriteInstance {},
	flechafinNivel4: class extends self.ISpriteInstance {},
	flechaNivel4: class extends self.ISpriteInstance {},
	IzquierdaNivel4: class extends self.ISpriteInstance {},
	JuegosNivel4: class extends self.ISpriteInstance {},
	M2AntenasNivel4: class extends self.ISpriteInstance {},
	M3AntenasNivel4: class extends self.ISpriteInstance {},
	M4AntenasNivel4: class extends self.ISpriteInstance {},
	M5AntenasNivel4: class extends self.ISpriteInstance {},
	mallaNivel4: class extends self.ISpriteInstance {},
	MonatñaNivel4: class extends self.ISpriteInstance {},
	montañainicioNivel4: class extends self.ISpriteInstance {},
	montañatileCompletoNivel4: class extends self.ISpriteInstance {},
	objetoBasuraNivel4: class extends self.ISpriteInstance {},
	PalomaNivel4: class extends self.ISpriteInstance {},
	PequeCiudadVirgenNivel4: class extends self.ISpriteInstance {},
	PequeciudSINVIRGENNivel4: class extends self.ITiledBackgroundInstance {},
	PremioNivel4: class extends self.ISpriteInstance {},
	RataNivel4: class extends self.ISpriteInstance {},
	roca2Nivel4: class extends self.ISpriteInstance {},
	rocas3Nivel4: class extends self.ISpriteInstance {},
	rocasNivel4: class extends self.ISpriteInstance {},
	slimeNivel4: class extends self.ISpriteInstance {},
	spr_TelefericoNivel4: class extends self.ISpriteInstance {},
	subirNivel4: class extends self.ISpriteInstance {},
	sueloNivel4: class extends self.ISpriteInstance {},
	tarjetaNivel4: class extends self.ISpriteInstance {},
	TextofinalNivel4: class extends self.ISpriteInstance {},
	textoinicioNivel4: class extends self.ISpriteInstance {},
	tierra_3Nivel4: class extends self.ITiledBackgroundInstance {},
	tierraMedianaNivel4: class extends self.ISpriteInstance {},
	tierraOscuraNivel4: class extends self.ISpriteInstance {},
	tierraPequeniaNivel4: class extends self.ISpriteInstance {},
	unioncableNivel4: class extends self.ISpriteInstance {},
	VioletaBajadaNivel4: class extends self.ISpriteInstance {},
	VioletaSubidaNivel4: class extends self.ISpriteInstance {},
	VolcanoNivel4: class extends self.ISpriteInstance {},
	vidaTextoNivel4: class extends self.ITextInstance {},
	numTarjetasNivel4: class extends self.ITextInstance {},
	pinchosNivel4: class extends self.ISpriteInstance {},
	XcierraNivel4: class extends self.ISpriteInstance {},
	arbusto1Nivel4: class extends self.ISpriteInstance {},
	arbusto2Nivel4: class extends self.ISpriteInstance {},
	arbusto3Nivel4: class extends self.ISpriteInstance {},
	arbusto4Nivel4: class extends self.ISpriteInstance {},
	dronNivel4: class extends self.ISpriteInstance {},
	telefericoNivel4: class extends self.ISpriteInstance {},
	SpriteFontCarnetNivel4: class extends self.ISpriteFontInstance {},
	SpriteFontNivel4: class extends self.ISpriteFontInstance {},
	PonkNivel4: class extends self.ISpriteInstance {},
	flechaNivel3: class extends self.ISpriteInstance {},
	msg2Nivel3: class extends self.ISpriteInstance {},
	msgNivel3: class extends self.ISpriteInstance {},
	TechoMitadNivel3: class extends self.ITiledBackgroundInstance {},
	CarnetColectNivel3: class extends self.ISpriteInstance {},
	CarnetNivel3: class extends self.ITextInstance {},
	CarnetsNivel3: class extends self.ISpriteInstance {},
	chicleNivel3: class extends self.ISpriteInstance {},
	deNivel3: class extends self.ISpriteInstance {},
	FondoEnMosaico2Nivel3: class extends self.ITiledBackgroundInstance {},
	FondoEnMosaico3Nivel3: class extends self.ITiledBackgroundInstance {},
	FondoNivel3: class extends self.ITiledBackgroundInstance {},
	IzqNivel3: class extends self.ISpriteInstance {},
	MetaNivel3: class extends self.ISpriteInstance {},
	PalomaNivel3: class extends self.ISpriteInstance {},
	ParedNivel3: class extends self.ISpriteInstance {},
	pisoNivel3: class extends self.ISpriteInstance {},
	EcosNivel3: class extends self.ISpriteInstance {},
	PremioNivel3: class extends self.ISpriteInstance {},
	PuertaNivel3: class extends self.ISpriteInstance {},
	RataNivel3: class extends self.ISpriteInstance {},
	SpriteNivel3: class extends self.ISpriteInstance {},
	VidaNivel3: class extends self.ISpriteInstance {},
	VidasNivel3: class extends self.ITextInstance {},
	materialToxicoNivel4: class extends self.ISpriteInstance {},
	nuevaHierbaAzulNivel3: class extends self.ISpriteInstance {},
	nuevaPlataformaDerechaNivel3: class extends self.ISpriteInstance {},
	nuevaPlataformaIzquierdaNivel3: class extends self.ISpriteInstance {},
	nuevaPlataformaNivel3: class extends self.ISpriteInstance {},
	nuevaPuertaFrenteNivel3: class extends self.ISpriteInstance {},
	nuevaPuertaJardinBotanicoFrenteNivel3: class extends self.ISpriteInstance {},
	nuevaPuertaNivel3: class extends self.ISpriteInstance {},
	nuevoArbol1Nivel3: class extends self.ISpriteInstance {},
	nuevoArbol2Nivel3: class extends self.ISpriteInstance {},
	nuevoArbol3Nivel3: class extends self.ISpriteInstance {},
	nuevoArbol4Nivel3: class extends self.ISpriteInstance {},
	nuevoArbolLamparaNivel3: class extends self.ISpriteInstance {},
	nuevoArbustoNivel3: class extends self.ISpriteInstance {},
	nuevoFondo1Nivel3: class extends self.ITiledBackgroundInstance {},
	nuevoFondoArbolesNivel3: class extends self.ITiledBackgroundInstance {},
	nuevoFondoLab1Nivel3: class extends self.ITiledBackgroundInstance {},
	nuevoFondoLab2Nivel3: class extends self.ITiledBackgroundInstance {},
	nuevoFondoLab3Nivel3: class extends self.ITiledBackgroundInstance {},
	nuevoFondoLabFinalNivel3: class extends self.ITiledBackgroundInstance {},
	nuevoFondoNivel4: class extends self.ITiledBackgroundInstance {},
	nuevoRellenoSuelo1Nivel3: class extends self.ISpriteInstance {},
	nuevoSLab1Nivel3: class extends self.ISpriteInstance {},
	nuevoSLab2Nivel3: class extends self.ISpriteInstance {},
	nuevoSLab3Nivel3: class extends self.ISpriteInstance {},
	nuevoSLab4Nivel3: class extends self.ISpriteInstance {},
	nuevoSLab5Nivel3: class extends self.ISpriteInstance {},
	nuevoSLab6Nivel3: class extends self.ISpriteInstance {},
	nuevoSLab7Nivel3: class extends self.ISpriteInstance {},
	nuevoSLab8Nivel3: class extends self.ISpriteInstance {},
	puertaJardinBotanicoNivel3: class extends self.ISpriteInstance {},
	sueloLab1Nivel3: class extends self.ITiledBackgroundInstance {},
	sueloLab2Nivel3: class extends self.ITiledBackgroundInstance {},
	sueloLab3Nivel3: class extends self.ITiledBackgroundInstance {},
	SpriteFontCarnetNivel3: class extends self.ISpriteFontInstance {},
	SpriteFontNivel3: class extends self.ISpriteFontInstance {},
	PonkNivel3: class extends self.ISpriteInstance {},
	AlcantarillaNivel5: class extends self.ISpriteInstance {},
	AlcantarrillaNivel5: class extends self.ISpriteInstance {},
	AvionNivel5: class extends self.ISpriteInstance {},
	basemilitarNivel5: class extends self.ISpriteInstance {},
	bomberosNivel5: class extends self.ISpriteInstance {},
	cabezaNivel5: class extends self.ISpriteInstance {},
	CalleNivel5: class extends self.ITiledBackgroundInstance {},
	CarnetesCuentaNivel5: class extends self.ISpriteInstance {},
	ContenedorRosaNivel5: class extends self.ISpriteInstance {},
	contenedorverdeNivel5: class extends self.ISpriteInstance {},
	EcosNivel5: class extends self.ISpriteInstance {},
	LamparaNivel5: class extends self.ISpriteInstance {},
	MetaNivel5: class extends self.ISpriteInstance {},
	MundoNivel5: class extends self.ISpriteInstance {},
	PalomaNivel5: class extends self.ISpriteInstance {},
	Plataforma2Nivel5: class extends self.ISpriteInstance {},
	PlataformaMuerteNivel5: class extends self.ISpriteInstance {},
	PlataformaNivel5: class extends self.ISpriteInstance {},
	plataformasNivel5: class extends self.ISpriteInstance {},
	PremioNivel5: class extends self.ISpriteInstance {},
	RataNivel5: class extends self.ISpriteInstance {},
	RosaPlanoNivel5: class extends self.ITiledBackgroundInstance {},
	RosaSEPARADONivel5: class extends self.ITiledBackgroundInstance {},
	salidametrofondoNivel5: class extends self.ISpriteInstance {},
	salidametrofrontalNivel5: class extends self.ISpriteInstance {},
	SlimeNivel5: class extends self.ISpriteInstance {},
	Sprite2Nivel5: class extends self.ISpriteInstance {},
	SpriteNivel5: class extends self.ISpriteInstance {},
	susbsueloNivel5: class extends self.ITiledBackgroundInstance {},
	tarjetaNivel5: class extends self.ISpriteInstance {},
	tarjetaTextoNivel5: class extends self.ITextInstance {},
	TodoCercaNivel5: class extends self.ITiledBackgroundInstance {},
	unsoloescenarioNivel5: class extends self.ITiledBackgroundInstance {},
	ventanabasemilitarNivel5: class extends self.ISpriteInstance {},
	VidaTextoNivel5: class extends self.ITextInstance {},
	flechafinNivel5: class extends self.ISpriteInstance {},
	FlechainicioNivel5: class extends self.ISpriteInstance {},
	TextofinalNivel5: class extends self.ISpriteInstance {},
	textoinicioNivel5: class extends self.ISpriteInstance {},
	FondoEnMosaico2: class extends self.ITiledBackgroundInstance {},
	arbusto1Nivel5: class extends self.ISpriteInstance {},
	arbusto2Nivel5: class extends self.ISpriteInstance {},
	arbusto3Nivel5: class extends self.ISpriteInstance {},
	arbusto4Nivel5: class extends self.ISpriteInstance {},
	basemilitarEntradaNivel5: class extends self.ISpriteInstance {},
	SpriteFontCarnetNivel5: class extends self.ISpriteFontInstance {},
	SpriteFontNivel5: class extends self.ISpriteFontInstance {},
	PonkNivel5: class extends self.ISpriteInstance {},
	beyonderNivel5: class extends self.ISpriteInstance {},
	dronNivel5: class extends self.ISpriteInstance {},
	AlmacenamientoLocal: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	CartelAdvertenciaBorradoSeleccionNivel: class extends self.ISpriteInstance {},
	FondoEnMosaico: class extends self.ITiledBackgroundInstance {},
	FondoSeleccion: class extends self.ITiledBackgroundInstance {},
	fondoTransparenteConfirmarBorrado: class extends self.ISpriteInstance {},
	IconoEliminarGuardado: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	NoBorrarProgresoSeleccionNivel: class extends self.ISpriteInstance {},
	SeleccionNivel1: class extends self.ISpriteInstance {},
	SeleccionNivel2: class extends self.ISpriteInstance {},
	SeleccionNivel3: class extends self.ISpriteInstance {},
	SeleccionNivel4: class extends self.ISpriteInstance {},
	SeleccionNivel5: class extends self.ISpriteInstance {},
	SiBorrarProgresoSeleccionNivel: class extends self.ISpriteInstance {},
	TituloSeleccionarNivel: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	volverMenuSeleccionNivel: class extends self.ISpriteInstance {},
	equis: class extends self.ISpriteInstance {},
	SeleccionNivel6: class extends self.ISpriteInstance {},
	logoEcos: class extends self.ISpriteInstance {},
	RataNivel0: class extends self.ISpriteInstance {},
	deNivel0: class extends self.ISpriteInstance {},
	IzqNivel0: class extends self.ISpriteInstance {},
	Navegador: class extends self.IInstance {},
	plataforma: class extends self.ISpriteInstance {},
	SeleccionarElNivel: class extends self.ITextInstance {},
	FuenteSprite: class extends self.ISpriteFontInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Texto_seleccion: class extends self.ISpriteInstance {},
	dienteDeLeon: class extends self.ISpriteInstance {},
	optimizado: class extends self.ISpriteInstance {}
}